# Generated by Django 5.2.3 on 2025-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='zipcode',
            field=models.CharField(default='06000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('elder', 'Elder'), ('volunteer', 'Volunteer'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
