# Generated by Django 5.2.3 on 2025-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cities_zipcode_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elders',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='url_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
